export const PRODUCT = {
  modelUrl: "/generator.glb",
  brand: "SHENCHAI POWER",
  stats: [
    { value: "IP 43", label: "PROTECTION" },
    { value: "−20 ~ 55°C", label: "OPERATING TEMP." },
    { value: "75", label: "dB(A) @ 1m" },
    { value: "5000h", label: "SERVICE LIFE" },
  ],
  footer: {
    copyright: "© 2026 深柴动力",
    series: "SCP · 500kW Series",
  },
  stages: [
    { id: "home", label: "深柴动力", cam: [-2, 1.5, 5], target: [0, 0, 0], fov: 40, rot: 0,
      subtitle: "SHENCHAI POWER · 始于 2004",
      desc: "专业柴油发电机组研发制造商，专注为客户提供可靠的电力解决方案" },
    { id: "allinone", label: "ALL-IN-ONE", cam: [0, 5, 7.5], target: [0, 0, 0], fov: 26, rot: -1.5,
      subtitle: "设计与快速部署",
      desc: "模块化布局，「出厂前整机测试，抵达现场后添加燃料连接电缆即可运行，将部署时间从数周缩短至几天" },
    { id: "engine", label: "动力系统稳定输出", cam: [0, 1.5, 6], target: [0, 0, 0], fov: 28, rot: 0,
      subtitle: "多元动力 · 按需匹配",
      desc: "提供全系列发动机品牌选择，满足不同应用场景，稳定输出每一瓦特" },
    { id: "airflow", label: "气流设计", cam: [-7.5, 5, 4.5], target: [0, 0, 0], fov: 24, rot: 1.5,
      subtitle: "AIRFLOW OPTIMIZATION",
      desc: "采用斜向导流进气结构，进气更加顺畅、排气阻力低、散热效率高" },
    { id: "chassis", label: "减震设计结构", cam: [-5.5, -1.5, 1.8], target: [0, 0.5, 0], fov: 30, rot: 3.0,
      subtitle: "强化底盘 · IP55 防护",
      desc: "强化底盘结构、高效减震系统、底盘IP55防护等级。为您考虑到了恶劣工况的使用环境，确保在任何情况下机组结构都能稳定运行" },
  ],
  copy: {
    zh: {
      navHome: "首页", navProducts: "产品中心", navAbout: "关于我们",
      navCases: "项目案例", navService: "销售与服务", scroll: "滚动探索",
      homeTitle: "静音型发电机组",
      homeIntro1: "深柴动力是一家集柴油发电机组研发、生产、销售和服务于一体的综合性企业。公司拥有现代化生产基地，年产能超过5000台套",
      homeIntro2: "依托自主技术、完善的质量体系与市场化创新机制，深柴动力已发展成为国内领先的柴油发电机组制造商",
      allinoneDesc: "模块化布局，出厂前整机测试，抵达现场后添加燃料连接电缆即可运行，将部署时间从数周缩短至几天",
      engineDesc: "提供全系列发动机品牌选择，满足不同应用场景",
      airflowDesc: "进气更加顺畅、排气阻力低、散热效率高",
      chassisDesc: "为您考虑到了恶劣工况的使用环境，确保在任何情况下机组结构都能稳定运行",
      homeBigTitle: "静音型发电机组",
      stage_home: "深柴动力",
      stage_allinone: "ALL-IN-ONE",
      stage_engine: "动力系统稳定输出",
      stage_airflow: "气流设计",
      stage_chassis: "减震设计结构",
      subHome: "SHENCHAI POWER · 始于 2004",
      sub_home: "SHENCHAI POWER · 始于 2004",
      sub_allinone: "设计与快速部署",
      sub_engine: "多元动力 · 按需匹配",
      sub_airflow: "AIRFLOW OPTIMIZATION",
      sub_chassis: "强化底盘 · IP55 防护",
    },
    en: {
      navHome: "Home", navProducts: "Products", navAbout: "About",
      navCases: "Projects", navService: "Service & Sales", scroll: "SCROLL",
      homeTitle: "Silent Generator Set",
      homeIntro1: "Shenchai Power is a comprehensive enterprise integrating R&D, production, sales and service of diesel generator sets. With a modern manufacturing base, annual capacity exceeds 5,000 units.",
      homeIntro2: "Backed by state-owned strength combined with market-oriented innovation, Shenchai Power has become a leading diesel generator set manufacturer in China.",
      allinoneDesc: "Modular layout, factory pre-tested. Add fuel and connect cables on site to start running, reducing deployment from weeks to days.",
      engineDesc: "Full range of engine brands available to meet diverse application scenarios.",
      airflowDesc: "Smoother intake, lower exhaust resistance, higher cooling efficiency.",
      chassisDesc: "Designed for harsh working conditions, ensuring stable operation of the unit in any environment.",
      homeBigTitle: "Silent Generator Set",
      stage_home: "Shenchai Power",
      stage_allinone: "ALL-IN-ONE",
      stage_engine: "Engine System",
      stage_airflow: "Airflow Design",
      stage_chassis: "Chassis Structure",
      subHome: "SHENCHAI POWER · Since 2004",
      sub_home: "SHENCHAI POWER · Since 2004",
      sub_allinone: "Design & Fast Deployment",
      sub_engine: "Multiple Power · On Demand",
      sub_airflow: "AIRFLOW OPTIMIZATION",
      sub_chassis: "Reinforced Chassis · IP55",
    },
  },
};
